version: '3.2'
services:
  # DB**
  postgres:
    restart: always
    container_name: hakaton-pg
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hakaton

  # BACK
  back:
    build: ./back/
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hakaton
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres
    expose:
      - '8080'
    ports:
      - '8080:8080'

  # # FRONT
  # front:
  #   container_name: stride-front
  #   build: ./client
  #   ports:
  #     - '5173:5173'