spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hakaton
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: liquibase/db-hakaton-changelog.xml
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  mail:
    host: smtp.yandex.ru
    username: berezin-work@yandex.ru
    password: fnxcwoecbjfnfnap
    port: 465
    protocol: smtps
    subject: Письмо от FreedomDashboardTV
    recipients: egor1414148@gmail.com
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enables: true

minio:
  bucket: files
  url: http://localhost:9000
  accessKey: admin
  secretKey: admin